-- MySQL Script generated by MySQL Workbench
-- Fri Jun 26 10:50:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `inventario` ;

-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventario` DEFAULT CHARACTER SET utf8 ;
USE `inventario` ;

-- -----------------------------------------------------
-- Table `inventario`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`users` ;

CREATE TABLE IF NOT EXISTS `inventario`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `rank` VARCHAR(45) NOT NULL,
  `cadre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) UNIQUE NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `is_admin` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`units` ;

CREATE TABLE IF NOT EXISTS `inventario`.`units` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_unit` VARCHAR(200) NOT NULL,
  `initials_unit` VARCHAR(45) NOT NULL,
  `chief_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `chief_id`
    FOREIGN KEY (`chief_id`)
    REFERENCES `inventario`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`divisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`divisions` ;

CREATE TABLE IF NOT EXISTS `inventario`.`divisions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_division` VARCHAR(100) NOT NULL,
  `initials_division` VARCHAR(45) NOT NULL,
  `chief_division_id` INT NOT NULL,
  `division_unit_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `chief_divisions_id`
    FOREIGN KEY (`chief_division_id`)
    REFERENCES `inventario`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `division_unit_id`
    FOREIGN KEY (`division_unit_id`)
    REFERENCES `inventario`.`units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`parts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`parts` ;

CREATE TABLE IF NOT EXISTS `inventario`.`parts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_part` VARCHAR(100) NOT NULL,
  `division_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `divison_id`
    FOREIGN KEY (`division_id`)
    REFERENCES `inventario`.`divisions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`types_materials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`types_materials` ;

CREATE TABLE IF NOT EXISTS `inventario`.`types_materials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_type` VARCHAR(200) UNIQUE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`models_materials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`models_materials` ;

CREATE TABLE IF NOT EXISTS `inventario`.`models_materials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_model` VARCHAR(200) NOT NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `type_id`
    FOREIGN KEY (`type_id`)
    REFERENCES `inventario`.`types_materials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`manufacturers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`manufacturers` ;

CREATE TABLE IF NOT EXISTS `inventario`.`manufacturers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_manufacturer` VARCHAR(100) UNIQUE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`status` ;

CREATE TABLE IF NOT EXISTS `inventario`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_status` VARCHAR(45) UNIQUE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`materials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`materials` ;

CREATE TABLE IF NOT EXISTS `inventario`.`materials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model_id` INT NOT NULL,
  `type_material_id` INT NOT NULL,
  `manufacturer_id` INT,
  `fk_division_id` INT NOT NULL,
  `part_id` INT,
  `room` INT NULL,
  `origin` VARCHAR(45) NULL,
  `number_unit` INT UNIQUE NOT NULL,
  `number_bmp` INT UNIQUE NULL,
  `number_metallic` INT UNIQUE NULL,
  `number_serial` VARCHAR(100) NULL,
  `status_id` INT NOT NULL,
  `gmm_cautela` VARCHAR(100),
  `obs` VARCHAR(300) NULL,
  `qrcode` VARCHAR(200) UNIQUE NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `type_mat_id`
    FOREIGN KEY (`type_material_id`)
    REFERENCES `inventario`.`types_materials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `manufacturer_id`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `inventario`.`manufacturers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_division_id`
    FOREIGN KEY (`fk_division_id`)
    REFERENCES `inventario`.`divisions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `part_id`
    FOREIGN KEY (`part_id`)
    REFERENCES `inventario`.`parts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `model_id`
    FOREIGN KEY (`model_id`)
    REFERENCES `inventario`.`models_materials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `status_id`
    FOREIGN KEY (`status_id`)
    REFERENCES `inventario`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
